### ISSUE TITLE
Мислене дали MongoDB е подходящ избор

### ISSUE THREAD

**Issue by gdgenchev** [gdgenchev/FMI-Room-Reservation-WEB-Project#7]
Например:
Да имаме таблица Reservations, в която има ключ - име и стая, from и to. В тази таблица да добавяме или премахваме резервациите.
В MongoDB дали това ще е толкова интуитивно? В RDBMS можем да Join-нем няколко таблици, за да вземем доста информация, докато в MongoDB това или трябва да е наблъскано всичкото в Room документът, или да направим няколко документа и да си играем..
Най-добре ще е да минем към SQL сякаш? Още повече - SQL сме го учили, а това MongoDB ще ни стане лошо 😆

**Comment by tsvetinavasileva** [comment]
SQL

**Comment by gdgenchev** [comment]
Ще използваме SQL, защото ще ни е по-лесно(понеже сме го учили), а и това е изискване за проекта(в примерната документация)
